# Generated by Django 4.2.3 on 2023-07-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('appetizers', 'appetizers'), ('deserts', 'deserts'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
