# Generated by Django 4.2.3 on 2023-08-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('appetizers', 'appetizers'), ('beverages', 'beverages'), ('deserts', 'deserts')], max_length=60),
        ),
    ]
