# Generated by Django 4.2.3 on 2023-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('deserts', 'deserts'), ('appetizers', 'appetizers'), ('entrees', 'entrees'), ('beverages', 'beverages')], max_length=60),
        ),
    ]
